sudo: false

language: php

matrix:
  include:
    - name: '[REQUIRE_CHECK] With Locked Dependencies'
      php: '7.4snapshot'
      env: require=1
    - name: '[REQUIRE_CHECK] With Lowest Dependencies'
      php: '7.4snapshot'
      env: require=1 dependencies=lowest
    - name: '[REQUIRE_CHECK] With Highest Dependencies'
      php: '7.4snapshot'
      env: require=1 dependencies=highest

    - name: '[CS] PHP 7.4 With Locked Dependencies'
      php: '7.4snapshot'
      env: cs=1
    - name: '[CS] PHP 7.4 With Lowest Dependencies'
      php: '7.4snapshot'
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP 7.4 With Highest Dependencies'
      php: '7.4snapshot'
      env: cs=1 dependencies=highest
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With Highest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest

    - name: '[UNIT] PHP 7.4 With Locked Dependencies'
      php: '7.4snapshot'
      env: unit=1
    - name: '[UNIT] PHP 7.4 With Lowest Dependencies'
      php: '7.4snapshot'
      env: dependencies=lowest unit=1
    - name: '[UNIT] PHP 7.4 With Highest Dependencies'
      php: '7.4snapshot'
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
      env: unit=1
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest unit=1

    - name: '[INTEGRATION] PHP 7.4 With Locked Dependencies'
      php: '7.4snapshot'
      env: integration=1
    - name: '[INTEGRATION] PHP 7.4 With Lowest Dependencies'
      php: '7.4snapshot'
      env: dependencies=lowest integration=1
    - name: '[INTEGRATION] PHP 7.4 With Highest Dependencies'
      php: '7.4snapshot'
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: integration=1
    - name: '[INTEGRATION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest integration=1

    - name: '[PHPSTAN] PHP 7.4 With Locked Dependencies'
      php: '7.4snapshot'
      env: phpstan=1
    - name: '[PHPSTAN] PHP 7.4 With Lowest Dependencies'
      php: '7.4snapshot'
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP 7.4 With Highest Dependencies'
      php: '7.4snapshot'
      env: phpstan=1 dependencies=highest
    - name: '[PHPSTAN] PHP Nightly With Locked Dependencies'
      php: nightly
      env: phpstan=1
    - name: '[PHPSTAN] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP Nightly With Highest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=highest
  allow_failures:
    - name: '[CS] PHP Nightly With Locked Dependencies'
      php: nightly
      env: cs=1
    - name: '[CS] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: cs=1 dependencies=lowest
    - name: '[CS] PHP Nightly With Highest Dependencies'
      php: nightly
      env: cs=1 dependencies=highest
    - name: '[UNIT] PHP Nightly With Locked Dependencies'
      php: nightly
      env: unit=1
    - name: '[UNIT] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest unit=1
    - name: '[UNIT] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest unit=1
    - name: '[INTEGRATION] PHP Nightly With Locked Dependencies'
      php: nightly
      env: integration=1
    - name: '[INTEGRATION] PHP Nightly With Highest Dependencies'
      php: nightly
      env: dependencies=highest integration=1
    - name: '[INTEGRATION] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: dependencies=lowest integration=1
    - name: '[PHPSTAN] PHP Nightly With Locked Dependencies'
      php: nightly
      env: phpstan=1
    - name: '[PHPSTAN] PHP Nightly With Lowest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=lowest
    - name: '[PHPSTAN] PHP Nightly With Highest Dependencies'
      php: nightly
      env: phpstan=1 dependencies=highest

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."
  - composer self-update

install:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
  - chmod +x php-coveralls.phar

before_script:
  - if [ -z "$dependencies" ]; then travis_retry composer install -n; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update -n; fi;

script:
  - if [ "$unit" = 1 ]; then phpdbg -qrr vendor/bin/phpunit --testsuite PeeHaaMigresUnitTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ "$integration" = 1 ]; then phpdbg -qrr vendor/bin/phpunit --testsuite PeeHaaMigresIntegrationTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ "$cs" = 1 ]; then vendor/bin/phpcs -s; fi;
  - if [ "$require" = 1 ]; then vendor/bin/composer-require-checker check; fi;
  - if [ "$phpstan" = 1 ]; then vendor/bin/phpstan analyse src --level max; fi;

after_success:
  - if [ "$unit" = 1 ]; then travis_retry php php-coveralls.phar; fi;
